namespace Volcano.Model
{
    /// <summary>
    /// Provides a semantic definition of the different palettes available in an Ultima 7 engine game.
    /// </summary>
    /// <remarks>
    /// Of course, the Ultima 7 graphics are palettized to 256 color palettes. Different effects are generated by using
    /// different palettes. These definitions were taken from the Exult source code.
    /// </remarks>
    public enum Palettes
    {
        /// <summary>
        /// The palette to use during the day.
        /// </summary>
        Day = 0,

        /// <summary>
        /// The palette to use at dusk.
        /// </summary>
        Dusk = 1,

        /// <summary>
        /// The palette to use at dawn.
        /// </summary>
        /// <remarks>
        /// From exult: Think this is it.
        /// </remarks>
        Dawn = 1, 

        /// <summary>
        /// The palette to use at night.
        /// </summary>
        Night = 2,

        /// <summary>
        /// The palette to use while invisible.
        /// </summary>
        Invisible = 3,

        /// <summary>
        /// The palette to use when it's overcast.
        /// </summary>
        Overcast = 4,

        /// <summary>
        /// The palette to use for fog.
        /// </summary>
        Fog = 5,

        // 6 looks a little brighter than #2.
        // 7 is somewhat warmer.  Torch?

        /// <summary>
        /// The palette to use when hit in combat.
        /// </summary>
        Red = 8,  // Used when hit in combat.
        
        // 9 has lots of black.
        
        /// <summary>
        /// The palette to use during a lightning flash.
        /// </summary>
        Lightning = 10,

        /// <summary>
        /// The palette to use when there's only one light.
        /// </summary>
        SingleLight = 11,

        /// <summary>
        /// The palette to use when there are many lights.
        /// </summary>
        ManyLights = 12,
    }
}
